version: "3"
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: booker
      MONGO_INITDB_ROOT_PASSWORD: 1234isnonsecure
    ports:
      - 27017:27017
  server:
    build: .
    ports:
      - 3030:3030
    depends_on:
      - mongo
    env_file:
      - .env
